<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$AESHelper = $this->helper('Custom\AESHelper\Helper\Data');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_request = $objectManager->get('\Magento\Framework\App\Request\Http');
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */
$_item = $block->getSaleableItem();
/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');
$tier_price = $block->getPriceType('tier_price');
/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;

	$saleName = '';
	$attributeSetId = $_item->getData('attribute_set_id');
	if ($attributeSetId == 25 ||  $attributeSetId == 27){
		 $saleName = 'Starting At';
	}else{
		$saleName = 'Sale';
	 }
?>
<?php if ($block->hasSpecialPrice() && ($_request->getFullActionName() != 'catalog_product_compare_index')): ?>
    <?php if($tier_price->getAmount() != ''): ?>

<?php if($block->getReretailPrice() != ''): ?>
<span class="old-price">      
<span class="price-container price-final_price tax weee">
            <span class="price-label">Orig</span>
        <span id="old-price" data-price-type="oldPrice" class="price-wrapper "><span class="price">$<?php echo substr($block->getReretailPrice(), 0, -2);?></span></span>
        </span>
    </span> 
    <?php endif;?>   

    <span class="tier-price special-sale">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Sale'),
            'price_id'          => $block->getPriceId('tier-price-' . $idSuffix),
            'price_type'        => 'tierPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
    <?php else: ?>

        <?php if($block->getReretailPrice() != ''): ?>
   <div class="lined_up">
<span class="old-price">
<span class="price-container price-final_price tax weee">
            <span class="price-label">Orig</span>
        <span id="old-price" data-price-type="oldPrice" class="price-wrapper "><span class="price">$<?php echo substr($block->getReretailPrice(), 0, -2);?></span></span>
        </span>
    </span>
    </div>
    <?php endif;?>

    <?php endif;?>
    <?php if($tier_price->getAmount() == ''): ?>

     <span class="tier-price special-sale">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Sale'),
            'price_id'          => $block->getPriceId('tier-price-' . $idSuffix),
            'price_type'        => 'tierPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
        
    <span class="special-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Clearance'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
    <?php else: ?>
    <span class="special-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Clearance'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
    <?php endif; ?>
    <?php       
        if ($_request->getFullActionName() == 'catalog_product_view') {
            echo $AESHelper->getPercentage($_item); 
        }
    ?>
   <!--  <div class="saving-price"><span class="saving-text"></span>
    <?php
        $wasPrice = $priceModel->getValue();
        $nowPrice = $finalPriceModel->getValue();
          if ($nowPrice < $wasPrice){
            $saving = $wasPrice - $nowPrice; 
            $saving = number_format((float)($wasPrice - $nowPrice), 2, '.', '');
            $savingper = number_format((float)(100*(($wasPrice - $nowPrice)/$wasPrice)), 0);
            echo '<span class="saving-wrapper">'.$savingper.'% OFF</span>';
          }
    ?>
    </div> -->
<?php else: ?>

    <?php if($block->getReretailPrice() != ''): ?>
   <div class="lined_up">
<span class="old-price">
<span class="price-container price-final_price tax weee">
            <span class="price-label">Orig</span>
        <span id="old-price" data-price-type="oldPrice" class="price-wrapper "><span class="price">$<?php echo substr($block->getReretailPrice(), 0, -2);?></span></span>
        </span>
    </span>
    </div>
    <?php endif;?>

    <span class="special-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __($saleName),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
    
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </a>
    <?php else:?>
        <div class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </div>
    <?php endif?>
<?php endif; ?>
