<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox$block */

/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
$label=__('Sale');
?>
<span class="retail-price sly-retail-price" style="font-size: 16px !important;line-height: 1;font-weight: 400;    text-decoration: line-through !important;color: #999;">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Orig'),
            'price_id'          => $block->getPriceId('retail-price-' . $idSuffix),
            'price_type'        => 'retailPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>


<?php 

   if (!$block->isProductList() && $block->hasSpecialPrice()):
	$label=__('Clearance');
 ?>
	    <span class="old-price sly-old-price no-display">
		<?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
		    'display_label'     => __('Sale'),
		    'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
		    'price_type'        => 'oldPrice',
		    'include_container' => true,
		    'skip_adjustments'  => true
		]); ?>
	    </span>
<?php endif; ?>

<span class="normal-price">
    <?php
        $arguments = [
            'display_label' => $label,
            'price_id' => $block->getPriceId('product-price-' . $idSuffix),
            'price_type' => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ];

        /* @noEscape */ echo $block->renderAmount($finalPriceModel->getAmount(), $arguments);
    ?>
</span>
<span class="percentage" style='display:none'><span class="percentage-price"> </span></span>
<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>
<script>
window.currentProductId='<?= $idSuffix ?>'
</script>


<style>
.retail-price .price-label {
    font-size: 16px !important;
    line-height: 1;
    font-weight: 400 !important;
    text-decoration: line-through !important;
    color: #999 !important;
}
</style>
